CPUS="2"
MEMORY="1024"

Vagrant.configure("2") do |config|

  config.vm.box = "centos/8"
  config.vm.hostname = "master.puppet.vm"
  config.vm.network "private_network", ip: "192.168.33.10"
  #config.vm.synced_folder "./GuestRootFS", "/vagrant"
  config.vm.provider "virtualbox" do |v|
    v.name = "master.puppet.vm"
    v.memory = MEMORY
    v.cpus = CPUS
  end

end
